---
# 파일명: nginx_reload.yml
- name: Manage nginx config
  hosts: local
  become: yes
  tasks:
    - name: Copy new nginx.conf
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
