all:
  children:
    webserver:           # 그룹 이름 (원하는 대로 정할 수 있습니다)
      hosts:
        172.16.194.131:  # 접속할 서버의 실제 IP 주소
    
    hue:                 # 또 다른 그룹 예시
      hosts:
        hue-server:      # 호스트 이름
